name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: dongmin90/github-actions-app
        tags: v3, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 'Deploy to Azure Web App'      
      uses: azure/webapps-deploy@v2      
      with:         
        app-name: 'WebappGithubActionJsy11' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
        images: 'dongmin90/github-actions-app:${{ github.sha }}'        
        
# name: Python application

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#         python-version: ['3.6', '3.8']
#         exclude:
#           - os: macos-latest
#             python-version: '3.8'
#           - os: windows-latest
#             python-version: '3.6'

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Display Python version
#       run: python -c "import sys; print(sys.version)"
